version: '3'

services:
  db:
    container_name: postgresdb
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.prod      
    volumes:
      - ./database_backups:/database_backups
  
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  web:
    container_name: remanga
    build: .
    command: gunicorn remanga_site.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file:
      - .env.prod         
    depends_on:
      - db
      - redis

  celery:
    container_name: celery
    build: .
    command: celery -A remanga_site worker -l INFO
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis