version: '3'

services:
  db:
    container_name: postgresdb
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=remanga
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Qewads
    ports:
      - 5432:5432
    volumes:
      - ./database_data:/var/lib/postgresql/data
      - ./database_backups:/database_backups
  
  web:
    container_name: remanga
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db