# Generated by Django 4.2.1 on 2023-12-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0002_remove_title_avg_rating_remove_title_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='titles',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
