# Generated by Django 4.2.1 on 2023-12-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0003_remove_user_titles_delete_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus_name', models.CharField(default='', max_length=100)),
                ('dir_name', models.CharField(default='', max_length=100)),
                ('img_url', models.CharField(default='', max_length=100)),
                ('manga_type', models.CharField(default='', max_length=100)),
                ('total_views', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('count_rating', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('issue_year', models.IntegerField(default=0)),
                ('count_bookmarks', models.IntegerField(default=0)),
                ('count_chapters', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=1500)),
                ('categories', models.ManyToManyField(to='remanga.categories')),
                ('chapters', models.ManyToManyField(to='remanga.chapters')),
                ('genres', models.ManyToManyField(to='remanga.genres')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='titles',
            field=models.ManyToManyField(to='remanga.title'),
        ),
    ]
