# Generated by Django 4.2.1 on 2023-12-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0007_remove_title_count_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='count_bookmarks',
            field=models.IntegerField(default=0),
        ),
    ]
