# Generated by Django 4.2.1 on 2023-12-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0015_comment_title_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Title_comments_ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_id', models.IntegerField(default=0)),
                ('comments_dislikes', models.ManyToManyField(related_name='comments_dislikes', to='remanga.comment')),
                ('comments_likes', models.ManyToManyField(related_name='comments_likes', to='remanga.comment')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='titles_comments_ratings',
            field=models.ManyToManyField(to='remanga.title_comments_ratings'),
        ),
    ]
