# Generated by Django 5.0 on 2023-12-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0017_remove_user_ratings_title_rating_delete_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title_rating',
            old_name='title_id',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='title_rating',
            old_name='user_id',
            new_name='user',
        ),
    ]
