# Generated by Django 5.0 on 2023-12-29 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0018_rename_title_id_title_rating_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='chapters',
        ),
        migrations.CreateModel(
            name='Title_chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('tome', models.IntegerField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='remanga.title')),
            ],
            options={
                'ordering': ['-tome', '-chapter'],
            },
        ),
    ]
