# Generated by Django 5.0 on 2023-12-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0019_remove_title_chapters_title_chapters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapters',
        ),
    ]
