# Generated by Django 5.0 on 2023-12-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0020_delete_chapters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='titles',
            new_name='bookmarks',
        ),
    ]
