# Generated by Django 5.0 on 2023-12-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0021_rename_titles_user_bookmarks'),
    ]

    operations = [
        
    ]
