# Generated by Django 4.2.1 on 2023-12-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0004_title_user_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='title',
            name='count_bookmarks',
        ),
        migrations.RemoveField(
            model_name='title',
            name='count_rating',
        ),
        migrations.RemoveField(
            model_name='title',
            name='total_views',
        ),
        migrations.RemoveField(
            model_name='title',
            name='total_votes',
        ),
    ]
