# Generated by Django 4.2.1 on 2023-12-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0006_title_avg_rating_title_count_bookmarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='count_bookmarks',
        ),
    ]
