# Generated by Django 4.2.1 on 2023-12-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0009_rating_title_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='title',
            name='ratings',
        ),
        migrations.AddField(
            model_name='rating',
            name='title_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ratings',
            field=models.ManyToManyField(to='remanga.rating'),
        ),
    ]
