# Generated by Django 4.2.1 on 2023-12-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0010_remove_rating_user_remove_title_ratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ratings',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
