# Generated by Django 4.2.1 on 2023-12-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0011_remove_user_ratings_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_id', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ratings',
            field=models.ManyToManyField(to='remanga.rating'),
        ),
    ]
