# Generated by Django 4.2.1 on 2023-12-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remanga', '0012_rating_user_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='blabla.jpg', upload_to='users_avatars'),
        ),
    ]
